### PR TITLE
Adding run method

### PR DESCRIPTION
**Pull request by natebrunette**
The run() method wraps a callable with start() and end() calls and returns the
result of the callable.  Any arguments passed into the method after the
callable will be passed to the callable.

Signed-off-by: Nate Brunette <n@tebru.net>

### CODE REVIEW

**Comment by devster** [comment]
Hello, thx for your work!

I'm totally agree with your feature, but I don't like the use of your var $_ to link phpdoc
Some code review tools will detect this var as dead code
You can put the details about arguments in the method description, it would be totally fine :)

And only if you have extra time an update of the readme would be nice, but i'll merge it anyway

Thx again

**Comment by natebrunette** [comment]
I'll make those updates, thanks!

**Comment by devster** [comment]
Hello,

Just a little up to know if you will finish your pr? if not i'll do it myself when i'll have time, because this is a nice feature :)

Bye

**Comment by natebrunette** [comment]
Updated.  Sorry for the delay, got busy and forgot about it.

**Comment by devster** [comment]
Do not be sorry :) I thought you've forgotten about it, it was a little reminder :)

**Comment by natebrunette** [comment]
Does this look good to you?

**Comment by devster** [comment]
Perfect! thx I'll make a minor release

**Pull request merged**
